=== fvrb/otvoreno-racunarstvo/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://example.com/example.json",
    "type": "array",
    "title": "OR Muzeji",
    "description": "Skup muzeja za otvoreno raƒçunarstvo.",
    "items": {
        "type": "object",
        "title": "Muzej",
        "description": "Objekt koji sadrzi podatke o jednom muzeju.",
        "required": [
            "id",
            "nazivMuzeja",
            "drzava",
            "grad",
            "godinaOsnivanja",
            "tipMuzeja",
            "velicinaKolekcije",
            "posjetitelji",
            "izlozbeniProstor",
            "webStranica",
            "onlineSetnja",
            "eksponati"
        ],
        "properties": {
            "id": {
                "type": "integer",
                "title": "ID muzeja",
                "description": "ID muzeja"
            },
            "nazivMuzeja": {
                "type": "string",
                "title": "Naziv muzeja",
                "description": "Naziv muzeja."
            },
            "drzava": {
                "type": "string",
                "title": "Drzava",
                "description": "Drzava muzeja."
            },
            "grad": {
                "type": "string",
                "title": "Grad",
                "description": "Grad muzeja."
            },
            "godinaOsnivanja": {
                "type": "integer",
                "title": "Godina osnivanja",
                "description": "Godina osnivanja muzeja."
            },
            "tipMuzeja": {
                "type": "string",
                "title": "Tip muzeja",
                "description": "Tip muzeja."
            },
            "velicinaKolekcije": {
                "type": "integer",
                "title": "Velicina kolekcije",
                "description": "Broj izlozbenih primjeraka u muzeju."
            },
            "posjetitelji": {
                "type": "integer",
                "title": "Posjetitelji",
                "description": "Broj posjetitelja izracunat za 2023."
            },
            "izlozbeniProstor": {
                "type": "integer",
                "title": "Izlozbeni prostor",
                "description": "Velicina izlozbenog prostora u kvadratnim metrima."
            },
            "webStranica": {
                "type": "string",
                "title": "Web stranica",
                "description": "Web sjediste muzeja."
            },
            "onlineSetnja": {
                "type": "boolean",
                "title": "Online setnja",
                "description": "Dostupnost online setnje kroz muzej."
            },
            "eksponati": {
                "type": "array",
                "title": "Eksponati",
                "description": "Eksponati dostupni u muzeju.",
                "items": {
                    "type": "object",
                    "title": "Eksponat",
                    "description": "Objekt koji sadrzi podatke o jednom eksponatu.",
                    "required": [
                        "id",
                        "nazivEksponata",
                        "tipEksponata"
                    ],
                    "properties": {
                        "id": {
                            "type": "integer",
                            "title": "ID eksponata",
                            "description": "ID eksponata."
                        },
                        "nazivEksponata": {
                            "type": "string",
                            "title": "Naziv eksponata",
                            "description": "Naziv eksponata."
                        },
                        "tipEksponata": {
                            "type": "string",
                            "title": "Tip eksponata",
                            "description": "Tip eksponata."
                        }
                    }
                }
            }
        }
    }
}

=== fvrb/otvoreno-racunarstvo/muzeji.json
[
  {
    "id": 2,
    "nazivMuzeja": "National Museum of China",
    "drzava": "Kina",
    "grad": "Peking",
    "godinaOsnivanja": 2003,
    "tipMuzeja": "povijesni",
    "velicinaKolekcije": 1300000,
    "posjetitelji": 6765000,
    "izlozbeniProstor": 65000,
    "webStranica": "http://en.chnmuseum.cn/",
    "onlineSetnja": true,
    "eksponati": [
      {
        "id": 3,
        "nazivEksponata": "Simuwu ding",
        "tipEksponata": "arheoloski artefakt"
      },
      {
        "id": 4,
        "nazivEksponata": "Oslikana keramika kulture Yangshao",
        "tipEksponata": "arheoloski artefakt"
      }
    ]
  },
  {
    "id": 1,
    "nazivMuzeja": "Louvre",
    "drzava": "Francuska",
    "grad": "Pariz",
    "godinaOsnivanja": 1793,
    "tipMuzeja": "povijesni",
    "velicinaKolekcije": 615797,
    "posjetitelji": 8900000,
    "izlozbeniProstor": 72735,
    "webStranica": "https://www.louvre.fr/en",
    "onlineSetnja": true,
    "eksponati": [
      {
        "id": 1,
        "nazivEksponata": "Mona Lisa",
        "tipEksponata": "slika"
      },
      {
        "id": 2,
        "nazivEksponata": "Venus de Milo",
        "tipEksponata": "skulptura"
      }
    ]
  },
  {
    "id": 9,
    "nazivMuzeja": "Prado Museum",
    "drzava": "Spanjolska",
    "grad": "Madrid",
    "godinaOsnivanja": 1819,
    "tipMuzeja": "umjetnicki",
    "velicinaKolekcije": 20000,
    "posjetitelji": 3337550,
    "izlozbeniProstor": 25000,
    "webStranica": "https://www.museodelprado.es/en",
    "onlineSetnja": true,
    "eksponati": [
      {
        "id": 17,
        "nazivEksponata": "La maja desnuda",
        "tipEksponata": "slika"
      },
      {
        "id": 18,
        "nazivEksponata": "David and Goliath",
        "tipEksponata": "slika"
      }
    ]
  },
  {
    "id": 10,
    "nazivMuzeja": "National Museum of Korea",
    "drzava": "Juzna Koreja",
    "grad": "Seoul",
    "godinaOsnivanja": 1945,
    "tipMuzeja": "povijesni",
    "velicinaKolekcije": 310000,
    "posjetitelji": 4180000,
    "izlozbeniProstor": 27090,
    "webStranica": "https://www.museum.go.kr/site/eng/home",
    "onlineSetnja": true,
    "eksponati": [
      {
        "id": 19,
        "nazivEksponata": "Pensive Bodhisattva",
        "tipEksponata": "skulptura"
      },
      {
        "id": 20,
        "nazivEksponata": "Gyeongcheonsa Pagoda",
        "tipEksponata": "skulptura"
      }
    ]
  },
  {
    "id": 8,
    "nazivMuzeja": "The State Hermitage Museum",
    "drzava": "Rusija",
    "grad": "Sankt-Peterburg",
    "godinaOsnivanja": 1764,
    "tipMuzeja": "umjetnicki",
    "velicinaKolekcije": 3000000,
    "posjetitelji": 3273753,
    "izlozbeniProstor": 66842,
    "webStranica": "https://www.hermitagemuseum.org/wps/portal/hermitage/",
    "onlineSetnja": true,
    "eksponati": [
      {
        "id": 15,
        "nazivEksponata": "The Three Graces",
        "tipEksponata": "skulptura"
      },
      {
        "id": 16,
        "nazivEksponata": "Portrait of Nikolay Borisovich Yusupov",
        "tipEksponata": "slika"
      }
    ]
  },
  {
    "id": 5,
    "nazivMuzeja": "British Museum",
    "drzava": "Engleska",
    "grad": "London",
    "godinaOsnivanja": 1753,
    "tipMuzeja": "povijesni",
    "velicinaKolekcije": 8000000,
    "posjetitelji": 5820860,
    "izlozbeniProstor": 75000,
    "webStranica": "https://www.britishmuseum.org/",
    "onlineSetnja": true,
    "eksponati": [
      {
        "id": 9,
        "nazivEksponata": "The Elgin Marbles",
        "tipEksponata": "skulptura"
      },
      {
        "id": 10,
        "nazivEksponata": "Rosetta Stone",
        "tipEksponata": "stela"
      }
    ]
  },
  {
    "id": 3,
    "nazivMuzeja": "Vatican Museums",
    "drzava": "Vatikan",
    "grad": "Rim",
    "godinaOsnivanja": 1506,
    "tipMuzeja": "umjetnicki",
    "velicinaKolekcije": 70000,
    "posjetitelji": 6800000,
    "izlozbeniProstor": 43000,
    "webStranica": "https://www.museivaticani.va/",
    "onlineSetnja": true,
    "eksponati": [
      {
        "id": 5,
        "nazivEksponata": "The Last Judgment",
        "tipEksponata": "freska"
      },
      {
        "id": 6,
        "nazivEksponata": "The School of Athens",
        "tipEksponata": "freska"
      }
    ]
  },
  {
    "id": 6,
    "nazivMuzeja": "National Air and Space Museum",
    "drzava": "SAD",
    "grad": "Washington, D.C.",
    "godinaOsnivanja": 1946,
    "tipMuzeja": "znanstveni",
    "velicinaKolekcije": 60000,
    "posjetitelji": 3100000,
    "izlozbeniProstor": 71000,
    "webStranica": "https://airandspace.si.edu/",
    "onlineSetnja": true,
    "eksponati": [
      {
        "id": 11,
        "nazivEksponata": "Command module Columbia",
        "tipEksponata": "letjelica"
      },
      {
        "id": 12,
        "nazivEksponata": "1959 Chevrolet Corvette C1",
        "tipEksponata": "automobil"
      }
    ]
  },
  {
    "id": 7,
    "nazivMuzeja": "Rijksmuseum",
    "drzava": "Nizozemska",
    "grad": "Amsterdam",
    "godinaOsnivanja": 1798,
    "tipMuzeja": "umjetnicki",
    "velicinaKolekcije": 1000000,
    "posjetitelji": 2700000,
    "izlozbeniProstor": 12000,
    "webStranica": "https://www.rijksmuseum.nl/en",
    "onlineSetnja": true,
    "eksponati": [
      {
        "id": 14,
        "nazivEksponata": "The Milkmaid",
        "tipEksponata": "slika"
      },
      {
        "id": 13,
        "nazivEksponata": "Girl in a Blue Dress",
        "tipEksponata": "slika"
      }
    ]
  },
  {
    "id": 4,
    "nazivMuzeja": "National Museum of Anthropology",
    "drzava": "Meksiko",
    "grad": "Ciudad de Mexico",
    "godinaOsnivanja": 1964,
    "tipMuzeja": "arheoloski",
    "velicinaKolekcije": 600000,
    "posjetitelji": 2636352,
    "izlozbeniProstor": 33000,
    "webStranica": "https://www.mna.inah.gob.mx/",
    "onlineSetnja": false,
    "eksponati": [
      {
        "id": 7,
        "nazivEksponata": "La Malinche huipil",
        "tipEksponata": "nosnja"
      },
      {
        "id": 8,
        "nazivEksponata": "Aztec Sunstone",
        "tipEksponata": "skulptura"
      }
    ]
  }
]
